#!/bin/bash


./photojs shsshow2024 "SHS Show 2024" ./photojs https://photos.app.goo.gl/pHVqfQxZYQwm8xGz5
mv shsshow2024.js ../home/gallery

exit

./photojs olympiques2024 "Feux Olympiques 2024" https://photos.app.goo.gl/z7VC3KWs93gLouf76
mv olympiques2024.js  ../home/gallery

exit

./photojs nlights2024 "Northern Lights May 2024" https://photos.app.goo.gl/XsbwvNqZkVRRMHD39
mv nlights2024.js ../home/gallery

exit

./photojs vh2024out "Village Hall Exterior" https://photos.app.goo.gl/NaVpcY6JgRNd3vty6
mv vh2024out.js ../home/gallery

exit
./photojs vh2024in "Village Hall Interior" https://photos.app.goo.gl/L2iTANcqXbFpqCZX8



exit


./photojs playgroundequip2024 "Playground Equipment" https://photos.app.goo.gl/cJ6LrEaXxrXfVvrG9

exit


./photojs playgroundstart2023 "Playground Groundwork" https://photos.app.goo.gl/rEtGjw719NuSSNWy9

exit

./photojs shsshow2023 "SHS Show 2023" https://photos.app.goo.gl/g8aBXtJd6SEss3KE7
mv shsshow2023.js ../home/gallery

exit

./photojs vh2023 "Village Hall 2023" https://photos.app.goo.gl/Nc9w8PWFXjZFtAgp6
mv vh2023.js ../home/gallery

exit

./photojs biglunch2023 "Coronation Big Lunch" https://photos.app.goo.gl/iWBEY2EXn1VfUG2Y7
mv biglunch2023.js ../home/gallery

exit

./photojs platinumthu "Platinum Jubilee Thursday" https://photos.app.goo.gl/3LToL1775qVu2zAZ6
mv platinumthu.js ../home/gallery

./photojs platinumfri "Platinum Jubilee Friday" https://photos.app.goo.gl/gBGb4zYWRspQzmRJ6
mv platinumfri.js ../home/gallery

./photojs platinumsat "Platinum Jubilee Saturday" https://photos.app.goo.gl/QJ8Bp9KEkK9AoaBM9
mv platinumsat.js ../home/gallery

./photojs platinumsun "Platinum Jubilee Sunday" https://photos.app.goo.gl/GCJqf1DMDdrxr93t7
mv platinumsun.js ../home/gallery

#./photojs easter2022 "Easter Egg Hunt 2022" https://photos.app.goo.gl/xoSoSfVDK2QNs5tt8
# cp easter2022.js ../home/gallery


# ./photojs shsalbum "SHS" https://photos.app.goo.gl/vzLREFJpevXQBC14A

# ./photojs playgroundmarch21 "Playground Demolition" https://photos.app.goo.gl/XZrSWnTtwcHmGQ1k9


# ./photojs shop2020  "Christmas Shop 2020" https://photos.app.goo.gl/wvz5KosDbyWhJti69
# mv shop2020.js ../home/gallery

# ./photojs ve75  "VE75 May 2020" https://photos.app.goo.gl/AB1TurFPowecpk9VA
# mv ve75.js ../home/gallery


# ./photojs souldern2020 "Souldern 2020" https://photos.app.goo.gl/w6SxED3jdp23cAXr7
# mv souldern2020.js ../home/gallery

# ./photojs soulderng  "Souldern Gallery" https://goo.gl/photos/ELeaYPtjdQmcjFYo8
# mv soulderng.js ../home/gallery

# ./photojs queen90 "Queen 90" https://goo.gl/photos/vpNg622EYvpByJam6
# mv queen90.js ../home/gallery

# ./photojs "nbwgallery" "Nancy Bowles Wood" https://goo.gl/photos/XLb6n9fPZuGQf1q18
# mv nbwgallery.js ../home/gallery

# ./photojs wacky2016 "Souldern Wacky Races 2016" https://goo.gl/photos/U1JFfKSCVRDH7g5B6
# mv wacky2016.js ../home/gallery

# ./photojs easter2017 "Easter Egg Hunt 2017" https://goo.gl/photos/JKoHFsuWuqTUctWX9
# mv easter2017.js ../home/gallery

# ./photojs knockout2017 "Knockout 2017" https://goo.gl/photos/yZhPPmYm84d812d4A
# mv knockout2017.js ../home/gallery

# ./photojs wacky2018 "Souldern Wacky Races 2018" https://photos.app.goo.gl/CmyvBVvsJJfoeAfg9
# mv wacky2018.js ../home/gallery

# ./photojs sundaysch "Sunday School" https://photos.app.goo.gl/TGxXrrQZjTJ2JRrf7
# mv sundaysch.js ../home/gallery




### ./photojs sssc0405 "SSSC Baking Week 2020-04-05" https://photos.app.goo.gl/4vyjnxGKp9JSx7eJ6
### mv sssc0405.js ../home/gallery
