#!/bin/bash

./photojs shsalbum "SHS" https://photos.app.goo.gl/vzLREFJpevXQBC14A

# ./photojs playgroundmarch21 "Playground Demolition" https://photos.app.goo.gl/XZrSWnTtwcHmGQ1k9


# ./photojs shop2020  "Christmas Shop 2020" https://photos.app.goo.gl/wvz5KosDbyWhJti69
# mv shop2020.js ../home/gallery

# ./photojs ve75  "VE75 May 2020" https://photos.app.goo.gl/AB1TurFPowecpk9VA
# mv ve75.js ../home/gallery


# ./photojs souldern2020 "Souldern 2020" https://photos.app.goo.gl/w6SxED3jdp23cAXr7
# mv souldern2020.js ../home/gallery

# ./photojs soulderng  "Souldern Gallery" https://goo.gl/photos/ELeaYPtjdQmcjFYo8
# mv soulderng.js ../home/gallery

# ./photojs queen90 "Queen 90" https://goo.gl/photos/vpNg622EYvpByJam6
# mv queen90.js ../home/gallery

# ./photojs "nbwgallery" "Nancy Bowles Wood" https://goo.gl/photos/XLb6n9fPZuGQf1q18
# mv nbwgallery.js ../home/gallery

# ./photojs wacky2016 "Souldern Wacky Races 2016" https://goo.gl/photos/U1JFfKSCVRDH7g5B6
# mv wacky2016.js ../home/gallery

# ./photojs easter2017 "Easter Egg Hunt 2017" https://goo.gl/photos/JKoHFsuWuqTUctWX9
# mv easter2017.js ../home/gallery

# ./photojs knockout2017 "Knockout 2017" https://goo.gl/photos/yZhPPmYm84d812d4A
# mv knockout2017.js ../home/gallery

# ./photojs wacky2018 "Souldern Wacky Races 2018" https://photos.app.goo.gl/CmyvBVvsJJfoeAfg9
# mv wacky2018.js ../home/gallery

# ./photojs sundaysch "Sunday School" https://photos.app.goo.gl/TGxXrrQZjTJ2JRrf7
# mv sundaysch.js ../home/gallery




### ./photojs sssc0405 "SSSC Baking Week 2020-04-05" https://photos.app.goo.gl/4vyjnxGKp9JSx7eJ6
### mv sssc0405.js ../home/gallery
